#!/usr/bin/env python

import json
from base64 import b64decode
from argparse import ArgumentParser


def main(path):
    with open(path, 'r') as f:
        data = f.read()
    data = json.loads(data)

    out = []
    for k, v in data.items():
        out.append((b64decode(k), v))
    
    for k, v in sorted(out):
        print(k, v)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('path', type=str, help='path to file')
    args = parser.parse_args()

    main(args.path)
